apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: apatranobis59/backend:3.0
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              value: user1
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: DB_NAME
              value: studentdb
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: app-2
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP