apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
  labels:
    app: nginx
  namespace: app-1
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer